:feelpp: Feel++
= Benchmarking rigid bodies moving in fluids using {feelpp} Supplementary Material

Authors

 - Luca Berti
 - Vincent Chabannes
 - Laetitia Giraldi 
 - Christophe Prud'homme
  
The directories contain the supplementary material to reproduce the results of the paper
"Benchmarking rigid bodies moving in fluids using {feelpp}"

The benchmarks can be run from a Linux Ubintu 20.04 system or with a docker container.

We used {feelpp} v109 which can be cited as follows
++++
Christophe Prud'homme, Vincent Chabannes, Thibaut Metivet, Romain Hild, Trophime, Abdoulaye SAMAKE, Thomas Saigre, Philippe Ricka, & Luca Berti. (2021). feelpp/feelpp: Feel++ V109 (v0.109.0). Zenodo. https://doi.org/10.5281/zenodo.5718297
++++

The development version v110 can be used as well.

## {feelpp} Installation

### Install {feelpp} in Ubuntu 20.04

The installation procedure of {feelpp} is described https://docs.feelpp.org/user/0.109/install/index.html[here].

### Pull the docker container

.Pull the docker image
[source,sh]
----
docker pull ghcr.io/feelpp/feelpp:v0.110.0-alpha.3-focal
----

.Run the docker image
[source,sh]
----
docker run --rm -it ghcr.io/feelpp/feelpp:v0.110.0-alpha.3-focal
----

## Run the benchmarks

To run the benchmarks using 4 mpi processes

.Falling sphere in a  Stokes flow
[source,sh]
----
mpirun -np 4 feelpp_toolbox_fluid --case sphere
----

.Falling 3D prolate ellipsoid in a  Stokes flow
[source,sh]
----
mpirun -np 4 feelpp_toolbox_fluid --case ellipsoid_3d
----

.Falling 2d ellipsoid in a Laminar flow
[source,sh]
----
mpirun -np 4 feelpp_toolbox_fluid --case ellipsoid_2d
----

.Falling 2d cylinder in a Laminar flow
[source,sh]
----
mpirun -np 4 feelpp_toolbox_fluid --case cylinder_2d
----